name: readme BUILD

on:
    push:
        branches:
            - "main"
    schedule:
        - cron: '0 */6 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: get node
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - name: get pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7
                  run_install: false
            - name: cache
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - name: install deps
              run: pnpm install
            - name: build
              run: pnpm build
            - name: push
              uses: github-actions-x/commit@v2.9
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  push-branch: 'main'
                  commit-message: 'updated'
                  force-add: 'true'
